version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: production  # or development
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_ENV=production
    restart: unless-stopped
