aws_region = "us-east-1"
s3_bucket_name = "taha-ayari-bucket"
sns_topic_name = "taha-ayari-sns-topic"
sqs_queue_name = "taha-ayari-sqs-queue"
notification_email = "taha.ayari@iteam-univ.tn"

db_name      = "iteam"
db_user      = "iteam"
db_password  = "iteam@2025"
environment  = "prod"
vpc_id       = "vpc-xxxxxxxx"
allowed_cidr = "0.0.0.0/0"