apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-deployment.yaml
  - app-deployment.yaml
  - ingress.yaml

images:
  - name: aws-s3-manager
    newTag: latest

commonLabels:
  app: aws-s3-manager
  version: v1.0.0